config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :differents

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/different.rb
class Different < ActiveRecord::Base
    has_attached_file :photo, :styles => { :small => "150x150>" },
                  :url  => "/assets/different/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/different/:id/:style/:basename.:extension"

#validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :rating, :room_id, :user_idinteger)
    end
end

app/controllers/differents_controller.rb
class DifferentsController < ApplicationController
  before_action :set_different, only: [:show, :edit, :update, :destroy]

  # GET /differents
  # GET /differents.json
  def index
    @differents = Different.all
  end

  # GET /differents/1
  # GET /differents/1.json
  def show
  end

  # GET /differents/new
  def new
    @different = Different.new
  end

  # GET /differents/1/edit
  def edit
  end

  # POST /differents
  # POST /differents.json
  def create
    @different = Different.new(different_params)

    respond_to do |format|
      if @different.save
        format.html { redirect_to @different, notice: 'Different was successfully created.' }
        format.json { render :show, status: :created, location: @different }
      else
        format.html { render :new }
        format.json { render json: @different.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /differents/1
  # PATCH/PUT /differents/1.json
  def update
    respond_to do |format|
      if @different.update(different_params)
        format.html { redirect_to @different, notice: 'Different was successfully updated.' }
        format.json { render :show, status: :ok, location: @different }
      else
        format.html { render :edit }
        format.json { render json: @different.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /differents/1
  # DELETE /differents/1.json
  def destroy
    @different.destroy
    respond_to do |format|
      format.html { redirect_to differents_url, notice: 'Different was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_different
      @different = Different.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def different_params
      params.require(:different).permit(:photo, :room_name, :description, :picture, :room_type, :guests, :bedroom, :bed, :price, :houserules, :availability, :wifi)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/differents_helper.rb
module DifferentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :room_id %><br>
    <%= f.number_field :room_id %>
  </div>
  <div class="field">
    <%= f.label :user_idinteger %><br>
    <%= f.text_field :user_idinteger %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Rating</th>
      <th>Room</th>
      <th>User idinteger</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.rating %></td>
        <td><%= comment.room_id %></td>
        <td><%= comment.user_idinteger %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @comment.rating %>
</p>

<p>
  <strong>Room:</strong>
  <%= @comment.room_id %>
</p>

<p>
  <strong>User idinteger:</strong>
  <%= @comment.user_idinteger %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/differents/_form.html.erb
<%= form_for(@different, :html => { :multipart => true }) do |f| %>
  <% if @different.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@different.errors.count, "error") %> prohibited this different from being saved:</h2>

      <ul>
      <% @different.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_name %><br>
    <%= f.text_field :room_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.text_field :room_type %>
  </div>
  <div class="field">
    <%= f.label :guests %><br>
    <%= f.number_field :guests %>
  </div>
  <div class="field">
    <%= f.label :bedroom %><br>
    <%= f.number_field :bedroom %>
  </div>
  <div class="field">
    <%= f.label :bed %><br>
    <%= f.number_field :bed %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :houserules %><br>
    <%= f.text_field :houserules %>
  </div>
  <div class="field">
    <%= f.label :availability %><br>
    <%= f.number_field :availability %>
  </div>
  <div class="field">
    <%= f.label :wifi %><br>
    <%= f.check_box :wifi %>
  </div>
  <%= f.file_field :photo %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/differents/edit.html.erb
<h1>Editing Different</h1>

<%= render 'form' %>

<%= link_to 'Show', @different %> |
<%= link_to 'Back', differents_path %>

app/views/differents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Differents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Type</th>
      <th>Guests</th>
      <th>Bedroom</th>
      <th>Bed</th>
      <th>Price</th>
      <th>Houserules</th>
      <th>Availability</th>
      <th>Wifi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @differents.each do |different| %>
      <tr>
        <td><%= different.room_name %></td>
        <td><%= different.description %></td>
        <td><%= different.picture %></td>
        <td><%= different.room_type %></td>
        <td><%= different.guests %></td>
        <td><%= different.bedroom %></td>
        <td><%= different.bed %></td>
        <td><%= different.price %></td>
        <td><%= different.houserules %></td>
        <td><%= different.availability %></td>
        <td><%= different.wifi %></td>
        <td><%= link_to 'Show', different %></td>
        <td><%= link_to 'Edit', edit_different_path(different) %></td>
        <td><%= link_to 'Destroy', different, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Different', new_different_path %>

app/views/differents/new.html.erb
<h1>New Different</h1>

<%= render 'form' %>

<%= link_to 'Back', differents_path %>

app/views/differents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @different.room_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @different.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @different.picture %>
</p>

<p>
  <strong>Type:</strong>
  <%= @different.room_type %>
</p>

<p>
  <strong>Guests:</strong>
  <%= @different.guests %>
</p>

<p>
  <strong>Bedroom:</strong>
  <%= @different.bedroom %>
</p>

<p>
  <strong>Bed:</strong>
  <%= @different.bed %>
</p>

<p>
  <strong>Price:</strong>
  <%= @different.price %>
</p>

<p>
  <strong>Houserules:</strong>
  <%= @different.houserules %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @different.availability %>
</p>

<p>
  <strong>Wifi:</strong>
  <%= @different.wifi %>
</p>
<%= image_tag @different.photo.url(:small) %>
<%= link_to 'Edit', edit_different_path(@different) %> |
<%= link_to 'Back', differents_path %>
<%= link_to 'Comment', new_comment_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>